version: "3.9"
volumes:
  php-fpm-socket:
  db-store:
  psysh-store:

services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./backend
        target: /backend
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-netflix}
      - DB_USERNAME=${DB_USER:-phper}
      - DB_PASSWORD=${DB_PASS:-secret}
    networks:
      mynetwork:
        ipv4_address: 10.200.1.10

  web:
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./backend
        target: /backend
    networks:
      mynetwork:
        ipv4_address: 10.200.1.20

  db:
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    ports:
      - target: 3306
        published: ${DB_PORT:-3306}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_DATABASE=${DB_NAME:-netflix}
      - MYSQL_USER=${DB_USER:-phper}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}
    networks:
      mynetwork:
        ipv4_address: 10.200.1.30
    mem_limit: 512m
    cpus: 2

  frontend:
    build:
      context: .
      dockerfile: ./infra/docker/frontend/Dockerfile
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://netflix.localhost:8090
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    networks:
      mynetwork:
        ipv4_address: 10.200.1.50

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS:-secret}
    networks:
      mynetwork:
        ipv4_address: 10.200.1.40

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.1.0/24
